VEX_DIR=/home/paul/vine/VEX/
LIBASMIR_CXXFLAGS=-I/home/paul/vine/VEX//pub -I/home/paul/vine/src/include -g -O2
LIBASMIR_LDFLAGS=-L/home/paul/vine/VEX/ -L/home/paul/vine/src 
LIBASMIR_LIBS=-lasmir -lvex -lbfd -liberty
