VEX_DIR=/home/stephan/Vine/VEX/
LIBASMIR_CXXFLAGS=-I/home/stephan/Vine/VEX//pub -I/home/stephan/Vine/src/include -g -O2
LIBASMIR_LDFLAGS=-L/home/stephan/Vine/VEX/ -L/home/stephan/Vine/src 
LIBASMIR_LIBS=-lasmir -lvex -lbfd -liberty
